
export const EMPLEOS = [
    {
        id: "1", // Changed to string to match useParams
        titulo: "Analista de Datos",
        empresa: "TechCorp LATAM",
        ubicacion: "Ciudad de México",
        modalidad: "Híbrido",
        salario: "$80,000 - $120,000 MXN",
        salaryMin: 80000,
        salaryMax: 120000,
        currency: "MXN",
        descripcion: "Buscamos analista con experiencia en Python, SQL y visualización de datos. \n\nTechCorp es una empresa líder en soluciones tecnológicas...",
        tags: ["Python", "SQL", "Power BI"],
        requirements: ["Experiencia en Python", "SQL avanzado", "Power BI o Tableau", "Inglés intermedio"],
        responsibilities: ["Analizar grandes volúmenes de datos", "Crear dashboards interactivos", "Colaborar con equipos de producto"],
        benefits: ["Seguro de gastos médicos mayores", "Trabajo híbrido", "Bonos por desempeño"],
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=TC&backgroundColor=1890ff",
        imagen: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
        publicado: "Hace 2 días",
        companyDescription: "TechCorp LATAM es líder en innovación tecnológica, brindando soluciones de software a nivel global.",
        companyWebsite: "https://techcorp.example.com"
    },
    {
        id: "2",
        titulo: "Full Stack Developer",
        empresa: "Fintech Innovators",
        ubicacion: "Remoto",
        modalidad: "Remoto",
        salario: "$90,000 - $140,000 MXN",
        salaryMin: 90000,
        salaryMax: 140000,
        currency: "MXN",
        descripcion: "Desarrollador con dominio de React, Node.js y bases de datos para unirse a nuestro equipo de producto.",
        tags: ["React", "Node.js", "MongoDB"],
        requirements: ["3+ años en React y Node.js", "Experiencia con bases de datos NoSQL", "Conocimiento de AWS es un plus"],
        responsibilities: ["Desarrollar nuevas funcionalidades", "Mantener la arquitectura de microservicios", "Optimizar rendimiento"],
        benefits: ["100% Remoto", "Stock options", "Equipo de última generación"],
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=FI&backgroundColor=52c41a",
        imagen: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&h=250&fit=crop",
        publicado: "Hace 1 día",
        companyDescription: "Fintech Innovators está revolucionando la banca digital con tecnología de punta.",
        companyWebsite: "https://fintech.example.com"
    },
    {
        id: "3",
        titulo: "UX/UI Designer",
        empresa: "Design Studio MX",
        ubicacion: "Guadalajara",
        modalidad: "Presencial",
        salario: "$50,000 - $70,000 MXN",
        salaryMin: 50000,
        salaryMax: 70000,
        currency: "MXN",
        descripcion: "Diseñador creativo con experiencia en Figma y Design Systems para proyectos internacionales.",
        tags: ["Figma", "UI Design", "Prototyping"],
        requirements: ["Portafolio demostrable", "Experiencia con sistemas de diseño", "Atención al detalle"],
        responsibilities: ["Diseñar interfaces de usuario", "Crear prototipos interactivos", "Realizar pruebas de usabilidad"],
        benefits: ["Ambiente creativo", "Capacitación continua", "Viernes cortos"],
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=DS&backgroundColor=722ed1",
        imagen: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=250&fit=crop",
        publicado: "Hace 3 días",
        companyDescription: "Design Studio MX crea experiencias digitales memorables para marcas líderes.",
        companyWebsite: "https://designstudio.example.com"
    },
    {
        id: "4",
        titulo: "Product Manager",
        empresa: "AI Labs Colombia",
        ubicacion: "Bogotá",
        modalidad: "Híbrido",
        salario: "$4,000 - $6,000 USD",
        salaryMin: 4000,
        salaryMax: 6000,
        currency: "USD",
        descripcion: "Líder de producto con visión estratégica y experiencia en Agile para nuestra división de IA.",
        tags: ["Product", "Agile", "Roadmap"],
        requirements: ["Experiencia previa como PM", "Conocimiento de metodologías ágiles", "Inglés fluido"],
        responsibilities: ["Definir el roadmap de producto", "Priorizar el backlog", "Coordinar lanzamientos"],
        benefits: ["Salario en USD", "Viajes anuales", "Seguro internacional"],
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=AI&backgroundColor=faad14",
        imagen: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=400&h=250&fit=crop",
        publicado: "Hace 5 días",
        companyDescription: "AI Labs Colombia investiga y desarrolla soluciones de inteligencia artificial aplicada.",
        companyWebsite: "https://ailabs.example.com"
    },
    {
        id: "5",
        titulo: "Backend Engineer",
        empresa: "Cloud Solutions",
        ubicacion: "Monterrey",
        modalidad: "Híbrido",
        salario: "$70,000 - $100,000 MXN",
        salaryMin: 70000,
        salaryMax: 100000,
        currency: "MXN",
        descripcion: "Ingeniero backend experto en Java, microservicios y AWS para plataforma de alta escala.",
        tags: ["Java", "Spring Boot", "AWS"],
        requirements: ["5+ años en Java", "Experiencia con Spring Boot", "Certificación AWS deseable"],
        responsibilities: ["Diseñar APIs RESTful", "Implementar arquitecturas escalables", "Mentorear juniors"],
        benefits: ["Seguro de vida", "Fondo de ahorro", "Vales de despensa"],
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=CS&backgroundColor=1890ff",
        imagen: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=250&fit=crop",
        publicado: "Hace 4 días",
        companyDescription: "Cloud Solutions ayuda a empresas a migrar y optimizar su infraestructura en la nube.",
        companyWebsite: "https://cloudsolutions.example.com"
    },
    {
        id: "6",
        titulo: "Marketing Digital Manager",
        empresa: "E-Commerce Pro",
        ubicacion: "Lima",
        modalidad: "Remoto",
        salario: "S/ 8,000 - S/ 12,000",
        salaryMin: 8000,
        salaryMax: 12000,
        currency: "PEN",
        descripcion: "Estratega digital con expertise en SEO, SEM y analytics para liderar crecimiento.",
        tags: ["SEO", "Google Ads", "Analytics"],
        requirements: ["Experiencia en e-commerce", "Dominio de Google Analytics", "Creatividad y análisis"],
        responsibilities: ["Crear estrategias de marketing", "Optimizar el funnel de conversión", "Gestionar presupuesto"],
        benefits: ["Bonos por resultados", "Horario flexible", "Cursos pagados"],
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=EC&backgroundColor=52c41a",
        imagen: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&h=250&fit=crop",
        publicado: "Hace 1 día",
        companyDescription: "E-Commerce Pro es la plataforma líder para ventas en línea en la región.",
        companyWebsite: "https://ecommercepro.example.com"
    }
]
